### PR TITLE
Qira patches to QEMU version 3.1.0

### PR DESCRIPTION
**Pull request by Hamled**
# Summary
This updates Qira's QEMU patch to work with version 3.1.0.

# Details
The first commit is my recreation of [the original QEMU patch](https://github.com/qemu/qemu/compare/v2.5.1...geohot:qira), done manually because of the extent of changes between version 2.5.1 and 3.1.0.

The remaining commits are minimal changes to enable QEMU to build successfully.

I've tested this (with [related changes to Qira's build scripts](https://github.com/geohot/qira/pull/210)) and had some success getting it to build both in the Docker container for Ubuntu 16.04 and on Arch Linux.

# TODO
* Create a `v3.1.0-qira` branch pointing at the same commit from `v3.1.0` tag
* Edit this PR to be merged against that branch instead of `master`

# Notes
* I am not very familiar with Qira yet, so I can't fully test the functionality. I'm not seeing any error messages in Qira's terminal output or Chrome's console when running `docker/test.sh`, and the automated tests all pass (but those also passed on un-patched 3.1.0 so I think they're not very comprehensive).

### CODE REVIEW

**Comment by geohot** [comment]
Will merge if you change to not push to master.

**Comment by Hamled** [comment]
Which branch should it merge into? The qira branch is too out of date for this to merge correctly, I think.

**Comment by geohot** [comment]
Can you merge into a new branch? The one referenced in the main qira PR.

**Comment by Hamled** [comment]
I don't believe I have sufficient permissions on your fork to create a new branch for the PR to be merged into.

I think you'll need to do that part, and then I can update the PR (although I'd wager you also have access to modify the PR).

**Comment by geohot** [comment]
Merged into v3.1.0-qira. Thanks!

**Pull request closed without merging**
